### ISSUE TITLE
Project setup

### ISSUE THREAD

**Issue by levani** [GeoLab-Edu/Charity-Foundation-02#1]
- [x] შექმენით ცარიალი პროექტი `create-react-app` ის გამოყენებით.
- [x] შექმენით პროექტი firebase და firebase hosting ის საშუალებით ატვირთეთ ცარიელი პროექტი. გადაამწმეთ რომ დეპლოიმენთი მუშაობს და firebase ის დაგენერირებულ მისამართზე თქვენი აპლიკაცია იტვირთება
(firebase-ის ნაცვლად შესაძლებელია სხვა ჰოსტინგის გამოყენაც)

**Comment by shalva-k** [comment]
Done
