### ISSUE TITLE
header კომპონენტი

### ISSUE THREAD

**Issue by levani** [GeoLab-Edu/Charity-Foundation-02#2]
დიზაინის მიხედვით ასაწყობია საიტის ჰედერი და ჩამოსაშლელი მენიუ.

<img width="1392" alt="Screenshot 2021-02-18 at 13 44 08" src="https://user-images.githubusercontent.com/184472/108338290-8789a780-71ef-11eb-86b1-f1040ec2de9c.png">

**Comment by shalva-k** [comment]
Done
